update division set div_name = "English Division 1 (old)" where div_id = 4;
update division set div_name = "English Division 2 (old)" where div_id = 7;
update division set div_name = "English Division 3 (old)" where div_id = 6;
update division set div_name = "English Division 4" where div_id = 5;
update division set div_name = "English Premier" where div_id = 3;
update division set div_name = "Football League Championship" where div_id = 1;
update division set div_name = "Football League One" where div_id = 2;
update division set div_name = "Football League Two" where div_id = 8;

update team set team_name = "Shrewsbury" where team_id = 1;
update team set team_name = "Barnsley" where team_id = 2;
update team set team_name = "Norwich" where team_id = 3;
update team set team_name = "Blackburn" where team_id = 4;
update team set team_name = "C Palace" where team_id = 5;
update team set team_name = "Blackpool" where team_id = 6;
update team set team_name = "Hull" where team_id = 7;
update team set team_name = "Bolton" where team_id = 8;
update team set team_name = "Burnley" where team_id = 9;
update team set team_name = "Bristol R" where team_id = 10;
update team set team_name = "Bournemouth" where team_id = 11;
update team set team_name = "Cambridge" where team_id = 12;
update team set team_name = "Bury" where team_id = 13;
update team set team_name = "Carlisle" where team_id = 14;
update team set team_name = "Halifax" where team_id = 15;
update team set team_name = "Cheltenham" where team_id = 16;
update team set team_name = "Mansfield" where team_id = 17;
update team set team_name = "Chesterfield" where team_id = 18;
update team set team_name = "York" where team_id = 19;
update team set team_name = "Exeter" where team_id = 20;
update team set team_name = "Cardiff" where team_id = 21;
update team set team_name = "Fulham" where team_id = 22;
update team set team_name = "Crewe" where team_id = 23;
update team set team_name = "Gillingham" where team_id = 24;
update team set team_name = "Stockport" where team_id = 25;
update team set team_name = "Grimsby" where team_id = 26;
update team set team_name = "Preston" where team_id = 27;
update team set team_name = "Huddersfield" where team_id = 28;
update team set team_name = "Watford" where team_id = 29;
update team set team_name = "Kidderminster" where team_id = 30;
update team set team_name = "Torquay" where team_id = 31;
update team set team_name = "Lincoln" where team_id = 32;
update team set team_name = "Hartlepool" where team_id = 33;
update team set team_name = "Luton" where team_id = 34;
update team set team_name = "Notts Co" where team_id = 35;
update team set team_name = "MK Dons" where team_id = 36;
update team set team_name = "Tranmere" where team_id = 37;
update team set team_name = "Macclesfield" where team_id = 38;
update team set team_name = "Scunthorpe" where team_id = 39;
update team set team_name = "Millwall" where team_id = 40;
update team set team_name = "Reading" where team_id = 41;
update team set team_name = "Northampton" where team_id = 42;
update team set team_name = "Brentford" where team_id = 43;
update team set team_name = "Nottm Forest" where team_id = 44;
update team set team_name = "West Brom" where team_id = 45;
update team set team_name = "Oldham" where team_id = 46;
update team set team_name = "Port Vale" where team_id = 47;
update team set team_name = "Oxford" where team_id = 48;
update team set team_name = "Peterborough" where team_id = 49;
update team set team_name = "Plymouth" where team_id = 50;
update team set team_name = "Leyton Orient" where team_id = 51;
update team set team_name = "QPR" where team_id = 52;
update team set team_name = "Birmingham" where team_id = 53;
update team set team_name = "Rochdale" where team_id = 54;
update team set team_name = "Darlington" where team_id = 55;
update team set team_name = "Rotherham" where team_id = 56;
update team set team_name = "Walsall" where team_id = 57;
update team set team_name = "Sheff Utd" where team_id = 58;
update team set team_name = "Portsmouth" where team_id = 59;
update team set team_name = "Southend" where team_id = 60;
update team set team_name = "Brighton" where team_id = 61;
update team set team_name = "Stoke" where team_id = 62;
update team set team_name = "Wycombe" where team_id = 63;
update team set team_name = "Swansea" where team_id = 64;
update team set team_name = "Wigan" where team_id = 65;
update team set team_name = "Swindon" where team_id = 66;
update team set team_name = "Colchester" where team_id = 67;
update team set team_name = "Wrexham" where team_id = 68;
update team set team_name = "Bristol C" where team_id = 69;
update team set team_name = "Wolves" where team_id = 70;
update team set team_name = "Sheff Wed" where team_id = 71;
update team set team_name = "Charlton" where team_id = 72;
update team set team_name = "Man City" where team_id = 73;
update team set team_name = "Chelsea" where team_id = 74;
update team set team_name = "West Ham" where team_id = 75;
update team set team_name = "Coventry" where team_id = 76;
update team set team_name = "Middlesbro" where team_id = 77;
update team set team_name = "Derby" where team_id = 78;
update team set team_name = "Southampton" where team_id = 79;
update team set team_name = "Leeds" where team_id = 80;
update team set team_name = "Everton" where team_id = 81;
update team set team_name = "Leicester" where team_id = 82;
update team set team_name = "Aston Villa" where team_id = 83;
update team set team_name = "Liverpool" where team_id = 84;
update team set team_name = "Bradford" where team_id = 85;
update team set team_name = "Sunderland" where team_id = 86;
update team set team_name = "Arsenal" where team_id = 87;
update team set team_name = "Tottenham" where team_id = 88;
update team set team_name = "Ipswich" where team_id = 89;
update team set team_name = "Man Utd" where team_id = 90;
update team set team_name = "Newcastle" where team_id = 91;
update team set team_name = "Rushden" where team_id = 92;
update team set team_name = "Boston Utd" where team_id = 93;
update team set team_name = "Doncaster" where team_id = 94;
update team set team_name = "Yeovil" where team_id = 95;
update team set team_name = "Chester" where team_id = 96;
update team set team_name = "Accrington" where team_id = 97;
update team set team_name = "Hereford" where team_id = 98;
update team set team_name = "Morecambe" where team_id = 99;
update team set team_name = "Dag & Red" where team_id = 100;
update team set team_name = "Aldershot" where team_id = 101;
update team set team_name = "Burton" where team_id = 102;
update team set team_name = "Stevenage" where team_id = 103;
update team set team_name = "Crawley" where team_id = 104;
update team set team_name = "AFC Wimbledon" where team_id = 105;
update team set team_name = "Fleetwood" where team_id = 106;
update team set team_name = "Newport Co" where team_id = 107;
update team set team_name = "Scarborough" where team_id = 108;
update team set team_name = "Maidstone" where team_id = 110;
update team set team_name = "Southport" where team_id = 112;
update team set team_name = "Workington" where team_id = 113;
update team set team_name = "Barrow" where team_id = 114;
update team set team_name = "Bradford PA" where team_id = 115;
update team set team_name = "Gateshead" where team_id = 116;
update team set team_name = "Wimbledon" where team_id = 117;
update team set team_name = "Barnet" where team_id = 118;
update team set team_name = "Forest Green" where team_id = 119;
